/* KIT-TBR-01 BOM 数据 · E1.2 */
window.BOM = {
  meta: {
    kit: "KIT-TBR-01",
    version: "E1.2",
    name: "网球自动捡球机器人",
  },

  categories: [
    { id: "extrusion", name: "铝型材 2020", color: "#3d4450" },
    { id: "sheet", name: "钣金 / 铝板", color: "#8a9098" },
    { id: "motor", name: "电机 / 舵机", color: "#1a1c20" },
    { id: "drive", name: "轴承 / 轴 / 传动", color: "#6a7078" },
    { id: "print", name: "3D 打印件", color: "#c8ccd2" },
    { id: "fastener", name: "紧固件 / 连接件", color: "#e85d04" },
    { id: "elec", name: "电子模块", color: "#22d866" },
    { id: "wire", name: "线材接插件", color: "#b8d84a" },
  ],

  /* ── 部件目录 ── */
  parts: [
    /* 铝型材 */
    {
      id: "E-01",
      cat: "extrusion",
      name: "纵梁",
      spec: "2020 · L560mm",
      qty: 2,
      color: "#2b2e33",
      dims: "560 × 20 × 20",
      desc: "左右主梁，黑阳极氧化 2020 欧标型材",
      connects: ["F-01", "F-04", "ACC-CORNER", "PL-01"],
      model: { type: "extrusion", length: 0.56 },
    },
    {
      id: "E-02",
      cat: "extrusion",
      name: "后横梁",
      spec: "2020 · L420mm",
      qty: 1,
      color: "#2b2e33",
      dims: "420 × 20 × 20",
      desc: "后端封闭横梁",
      connects: ["F-01", "F-04", "ACC-CORNER"],
      model: { type: "extrusion", length: 0.42 },
    },
    {
      id: "E-03",
      cat: "extrusion",
      name: "中横梁",
      spec: "2020 · L420mm",
      qty: 1,
      color: "#2b2e33",
      dims: "420 × 20 × 20",
      desc: "电池仓分隔",
      connects: ["F-01", "F-04", "ACC-CORNER"],
      model: { type: "extrusion", length: 0.42 },
    },
    {
      id: "E-04",
      cat: "extrusion",
      name: "前横梁",
      spec: "2020 · L420mm",
      qty: 1,
      color: "#2b2e33",
      dims: "420 × 20 × 20",
      desc: "前轮 / 滚轮滑轨根",
      connects: ["F-01", "F-04", "ACC-CORNER", "E-07"],
      model: { type: "extrusion", length: 0.42 },
    },
    {
      id: "E-05",
      cat: "extrusion",
      name: "上装立柱",
      spec: "2020 · L100mm",
      qty: 4,
      color: "#2b2e33",
      dims: "100 × 20 × 20",
      desc: "平台顶 → 挡板横梁",
      connects: ["F-01", "F-04"],
      model: { type: "extrusion", length: 0.10 },
    },
    {
      id: "E-06",
      cat: "extrusion",
      name: "挡板横梁",
      spec: "2020 · L400mm",
      qty: 1,
      color: "#2b2e33",
      dims: "400 × 20 × 20",
      desc: "摄像头 + 挡板吊点",
      connects: ["F-03", "ACC-CORNER", "ST-cam"],
      model: { type: "extrusion", length: 0.40 },
    },
    {
      id: "E-07",
      cat: "extrusion",
      name: "滚轮滑轨",
      spec: "2020 · L180 + 30×8 长圆孔",
      qty: 2,
      color: "#2b2e33",
      dims: "180 × 20 × 20",
      desc: "配 M5 长圆孔，滚轮前后/高度调节",
      connects: ["F-01", "F-16", "F-04"],
      model: { type: "extrusion", length: 0.18, slot: true },
    },
    {
      id: "E-08",
      cat: "extrusion",
      name: "筐定位轨",
      spec: "2020 · L360mm",
      qty: 2,
      color: "#2b2e33",
      dims: "360 × 20 × 20",
      desc: "平台顶 Z 向定位",
      connects: ["F-01", "F-17"],
      model: { type: "extrusion", length: 0.36 },
    },

    /* 钣金 */
    {
      id: "PL-01",
      cat: "sheet",
      name: "底板",
      spec: "5052-H32 · t2.0 · 560×460",
      qty: 1,
      color: "#9aa1a8",
      dims: "560 × 460 × 2",
      desc: "主承力板；进料口/轮拱/电机让位/走线孔",
      connects: ["F-02", "F-05", "E-01", "BR-02"],
      model: { type: "baseplate" },
    },
    {
      id: "PL-02",
      cat: "sheet",
      name: "后舱围板",
      spec: "5052 · t1.5 · 高135",
      qty: 1,
      color: "#9aa1a8",
      dims: "约 460×135 + 侧板",
      desc: "只围后段功能舱，顶沿 EPDM 密封",
      connects: ["F-01", "F-04", "ACC-CORNER"],
      model: { type: "skirt" },
    },
    {
      id: "PL-03",
      cat: "sheet",
      name: "60° 挡板",
      spec: "t2.0 · 148×288 · 翻边36",
      qty: 1,
      color: "#9aa1a8",
      dims: "148 × 288 × 2",
      desc: "贴 0.8mm 橡胶垫；绕杆端螺丝 ±18°",
      connects: ["E-06", "F-01", "E-05"],
      model: { type: "deflector" },
    },

    /* 电机 */
    {
      id: "M-01",
      cat: "motor",
      name: "滚轮电机",
      spec: "JGB37-520 12V 178RPM",
      qty: 1,
      color: "#1a1c20",
      dims: "Ø37 减速箱 · 轴 Ø6 D型",
      desc: "有刷验证版，轴端 GT2 20T",
      connects: ["ST-motor", "F-09", "PU-01", "BL-01"],
      model: { type: "jgb37", rpm: 178 },
    },
    {
      id: "M-02",
      cat: "motor",
      name: "后驱电机",
      spec: "JGB37 12V 250RPM + 编码器",
      qty: 1,
      color: "#1a1c20",
      dims: "Ø37 · 编码器尾",
      desc: "驱动后通轴；编码器反馈",
      connects: ["ST-motor", "F-09", "PU-01", "BL-02"],
      model: { type: "jgb37", rpm: 250, encoder: true },
    },
    {
      id: "S-01",
      cat: "motor",
      name: "转向舵机",
      spec: "MG996R · ≥10kg·cm @6V",
      qty: 1,
      color: "#2a1810",
      dims: "40 × 20 × 38",
      desc: "金属齿数字舵机，独立 5V≥3A",
      connects: ["ST-servo", "F-09", "ST-knuckle"],
      model: { type: "mg996" },
    },

    /* 轴承传动 */
    {
      id: "BR-01",
      cat: "drive",
      name: "轴承 608-2RS",
      spec: "8×22×7 · 双面橡胶密封",
      qty: 8,
      color: "#b0b6bc",
      dims: "Ø22 × 7 · 孔 Ø8",
      desc: "滚轮轴×4、前轮×4",
      connects: ["ST-bearing", "SH-01", "ST-endcap"],
      model: { type: "bearing608" },
    },
    {
      id: "BR-02",
      cat: "drive",
      name: "带座轴承",
      spec: "UCP / 立式 · 内孔 Ø10",
      qty: 2,
      color: "#8a9098",
      dims: "内孔 Ø10",
      desc: "后驱通轴支承",
      connects: ["SH-02", "PL-01", "F-07"],
      model: { type: "pillow" },
    },
    {
      id: "SH-01",
      cat: "drive",
      name: "滚轮轴",
      spec: "Ø8×420 · 两端 M6+扁位",
      qty: 1,
      color: "#c0c6cc",
      dims: "Ø8 × 420",
      desc: "精磨/冷拔轴，贯穿 TPU 滚轮",
      connects: ["BR-01", "ST-endcap", "ST-tpu", "F-13", "F-14"],
      model: { type: "shaft", d: 0.008, len: 0.42 },
    },
    {
      id: "SH-02",
      cat: "drive",
      name: "后驱通轴",
      spec: "Ø10×460 · 卡簧槽",
      qty: 1,
      color: "#c0c6cc",
      dims: "Ø10 × 460",
      desc: "单电机通轴驱动两后轮",
      connects: ["BR-02", "PU-03", "F-15"],
      model: { type: "shaft", d: 0.010, len: 0.46 },
    },
    {
      id: "SH-03",
      cat: "drive",
      name: "前轮主销",
      spec: "Ø8×70",
      qty: 2,
      color: "#c0c6cc",
      dims: "Ø8 × 70",
      desc: "转向节主销",
      connects: ["ST-knuckle", "BR-01"],
      model: { type: "shaft", d: 0.008, len: 0.07 },
    },
    {
      id: "BL-01",
      cat: "drive",
      name: "滚轮同步带",
      spec: "GT2 闭环 · 200-2GT-6",
      qty: 1,
      color: "#1a1a1a",
      dims: "周长 ~200 · 宽 6",
      desc: "滚轮电机 → 滚轮轴 40T",
      connects: ["PU-01", "PU-02", "M-01"],
      model: { type: "belt", major: 0.045, minor: 0.028 },
    },
    {
      id: "BL-02",
      cat: "drive",
      name: "后驱同步带",
      spec: "GT2 闭环 · 中心距 ~50",
      qty: 1,
      color: "#1a1a1a",
      dims: "按中心距选周长",
      desc: "后驱电机 → 通轴 40T",
      connects: ["PU-01", "PU-03", "M-02"],
      model: { type: "belt", major: 0.042, minor: 0.026 },
    },
    {
      id: "PU-01",
      cat: "drive",
      name: "带轮 20T Ø6",
      spec: "GT2 · 孔 Ø6",
      qty: 2,
      color: "#8a9098",
      dims: "齿 20 · 孔 Ø6",
      desc: "两电机输出轴",
      connects: ["M-01", "M-02", "F-15"],
      model: { type: "pulley", teeth: 20, bore: 0.006 },
    },
    {
      id: "PU-02",
      cat: "drive",
      name: "带轮 40T Ø6",
      spec: "GT2 · 孔 Ø6",
      qty: 1,
      color: "#8a9098",
      dims: "齿 40 · 孔 Ø6",
      desc: "滚轮轴端",
      connects: ["SH-01", "BL-01", "F-15"],
      model: { type: "pulley", teeth: 40, bore: 0.006 },
    },
    {
      id: "PU-03",
      cat: "drive",
      name: "带轮 40T Ø10",
      spec: "GT2 · 孔 Ø10",
      qty: 1,
      color: "#8a9098",
      dims: "齿 40 · 孔 Ø10",
      desc: "后驱通轴",
      connects: ["SH-02", "BL-02", "F-15"],
      model: { type: "pulley", teeth: 40, bore: 0.010 },
    },

    /* 3D 打印 */
    {
      id: "ST-tpu",
      cat: "print",
      name: "TPU 滚轮套",
      spec: "TPU 95A · 外Ø140",
      qty: 1,
      color: "#3a3c40",
      dims: "外Ø140 内Ø120 宽352",
      stl: "../stl/tpu_roller_sleeve.stl",
      desc: "螺旋筋咬球，包铝管芯 Ø80",
      connects: ["SH-01", "BR-01", "ST-endcap"],
      model: { type: "tpu_sleeve" },
    },
    {
      id: "ST-guide",
      cat: "print",
      name: "弧道段",
      spec: "PETG · R135 · 4段",
      qty: 4,
      color: "#c8ccd2",
      dims: "R135 宽400 壁3+侧60",
      stl: "../stl/guide_arc_segment.stl",
      desc: "同轴上升通道，M3 对接",
      connects: ["ST-tpu", "F-09"],
      model: { type: "guide_arc" },
    },
    {
      id: "ST-bearing",
      cat: "print",
      name: "608 轴承座",
      spec: "PETG/ABS · 44×44×16",
      qty: 4,
      color: "#c8ccd2",
      dims: "44×44×16 孔Ø22",
      stl: "../stl/bearing_housing_608.stl",
      desc: "滚轮轴支承，孔铰至 Ø22.0–22.1",
      connects: ["BR-01", "SH-01", "F-07", "F-08"],
      model: { type: "bearing_house" },
    },
    {
      id: "ST-motor",
      cat: "print",
      name: "JGB37 电机座",
      spec: "PETG · 抱箍Ø37",
      qty: 2,
      color: "#c8ccd2",
      dims: "抱箍Ø37 + 法兰耳",
      stl: "../stl/motor_mount_jgb37.stl",
      desc: "电机法兰耳 M3 固定",
      connects: ["M-01", "M-02", "F-09", "F-11"],
      model: { type: "motor_mount" },
    },
    {
      id: "ST-knuckle",
      cat: "print",
      name: "转向节",
      spec: "PETG · 主销Ø8 臂长28",
      qty: 2,
      color: "#c8ccd2",
      dims: "主销Ø8 · 臂长28",
      stl: "../stl/steering_knuckle.stl",
      desc: "前轮转向节，横拉杆球头",
      connects: ["SH-03", "S-01", "BR-01", "F-08"],
      model: { type: "knuckle" },
    },
    {
      id: "ST-servo",
      cat: "print",
      name: "舵机座",
      spec: "PETG · 适配 40×20",
      qty: 1,
      color: "#c8ccd2",
      dims: "适配 MG996R 机体",
      stl: "../stl/servo_mount_mg996.stl",
      desc: "中置舵机安装座",
      connects: ["S-01", "F-09", "F-11"],
      model: { type: "servo_mount" },
    },
    {
      id: "ST-ecu",
      cat: "print",
      name: "电控盒",
      spec: "PETG · 110×60×48",
      qty: 1,
      color: "#c8ccd2",
      dims: "110 × 60 × 48",
      stl: "../stl/ecu_box.stl",
      desc: "密封舱体，开口朝上打印",
      connects: ["ST-lid", "F-11", "U-02"],
      model: { type: "ecu_box" },
    },
    {
      id: "ST-lid",
      cat: "print",
      name: "电控盖",
      spec: "PETG · 114×52×5",
      qty: 1,
      color: "#c8ccd2",
      dims: "114 × 52 × 5 + 唇边",
      stl: "../stl/ecu_lid.stl",
      desc: "唇边密封，4×M3 锁紧",
      connects: ["ST-ecu", "F-09"],
      model: { type: "ecu_lid" },
    },
    {
      id: "ST-cam",
      cat: "print",
      name: "摄像头支架",
      spec: "PETG · 夹 2020",
      qty: 1,
      color: "#c8ccd2",
      dims: "夹 2020 槽",
      stl: "../stl/camera_bracket.stl",
      desc: "夹持挡板横梁 E-06",
      connects: ["E-06", "U-03", "F-04"],
      model: { type: "cam_bracket" },
    },
    {
      id: "ST-tof",
      cat: "print",
      name: "ToF 支架",
      spec: "PETG · VL53 安装面",
      qty: 3,
      color: "#c8ccd2",
      dims: "VL53L1X 安装面",
      stl: "../stl/tof_bracket.stl",
      desc: "正中装摄像头横梁，左右前在前脸",
      connects: ["U-04", "F-12", "E-06"],
      model: { type: "tof_bracket" },
    },
    {
      id: "ST-wheel",
      cat: "print",
      name: "轮罩",
      spec: "PETG · 适配 Ø100",
      qty: 4,
      color: "#c8ccd2",
      dims: "适配 Ø100 轮",
      stl: "../stl/wheel_cover.stl",
      desc: "四轮外罩",
      connects: ["F-01"],
      model: { type: "wheel_cover" },
    },
    {
      id: "ST-finger",
      cat: "print",
      name: "护指条",
      spec: "PETG · 330×10×12",
      qty: 1,
      color: "#c8ccd2",
      dims: "330 × 10 × 12",
      stl: "../stl/finger_guard.stl",
      desc: "滚轮进料口护指",
      connects: ["ST-tpu", "PL-01"],
      model: { type: "finger" },
    },
    {
      id: "ST-corner",
      cat: "print",
      name: "筐角件",
      spec: "PETG · L 22×22×160",
      qty: 8,
      color: "#c8ccd2",
      dims: "L 22×22×160",
      stl: "../stl/basket_corner.stl",
      desc: "球筐四角竖直角件 ×8",
      connects: ["F-17", "E-08"],
      model: { type: "basket_corner" },
    },
    {
      id: "ST-endcap",
      cat: "print",
      name: "滚轮端盖",
      spec: "PETG · 轴承位 Ø22",
      qty: 2,
      color: "#c8ccd2",
      dims: "轴承位 Ø22",
      stl: "../stl/roller_endcap.stl",
      desc: "滚轮端盖，压 608",
      connects: ["BR-01", "ST-tpu", "SH-01"],
      model: { type: "endcap" },
    },

    /* 紧固件 / 连接件 */
    {
      id: "ACC-CORNER",
      cat: "fastener",
      name: "90° 角件",
      spec: "2020 用 · 铝合金",
      qty: 16,
      color: "#e85d04",
      dims: "标准 2020 角件",
      desc: "型材直角连接，配 M5×12",
      connects: ["F-01", "F-03", "F-04"],
      model: { type: "corner" },
    },
    {
      id: "F-01",
      cat: "fastener",
      name: "M5×10 内六角",
      spec: "圆柱头 8.8",
      qty: 40,
      color: "#c0c6cc",
      dims: "M5 × 10",
      desc: "型材 + T 螺母",
      connects: ["F-04", "ACC-CORNER"],
      model: { type: "screw", d: 0.005, len: 0.010, head: "socket" },
    },
    {
      id: "F-02",
      cat: "fastener",
      name: "M5×8 内六角",
      spec: "圆柱头",
      qty: 24,
      color: "#c0c6cc",
      dims: "M5 × 8",
      desc: "底板-型材",
      connects: ["F-05", "PL-01", "E-01"],
      model: { type: "screw", d: 0.005, len: 0.008, head: "socket" },
    },
    {
      id: "F-03",
      cat: "fastener",
      name: "M5×12 内六角",
      spec: "圆柱头",
      qty: 12,
      color: "#c0c6cc",
      dims: "M5 × 12",
      desc: "角件连接",
      connects: ["ACC-CORNER", "F-04"],
      model: { type: "screw", d: 0.005, len: 0.012, head: "socket" },
    },
    {
      id: "F-04",
      cat: "fastener",
      name: "M5 T 螺母",
      spec: "弹片式 · 2020 槽",
      qty: 50,
      color: "#9aa1a8",
      dims: "M5 弹片 T 母",
      desc: "滑入 2020 槽后旋紧",
      connects: ["F-01", "F-03", "E-01"],
      model: { type: "tnut" },
    },
    {
      id: "F-05",
      cat: "fastener",
      name: "M5 法兰螺母",
      spec: "—",
      qty: 24,
      color: "#9aa1a8",
      dims: "M5 法兰",
      desc: "底板背面",
      connects: ["F-02", "PL-01"],
      model: { type: "flange_nut" },
    },
    {
      id: "F-07",
      cat: "fastener",
      name: "M4×12 内六角",
      spec: "圆柱头",
      qty: 16,
      color: "#c0c6cc",
      dims: "M4 × 12",
      desc: "轴承座",
      connects: ["F-08", "ST-bearing"],
      model: { type: "screw", d: 0.004, len: 0.012, head: "socket" },
    },
    {
      id: "F-08",
      cat: "fastener",
      name: "M4 热熔螺母",
      spec: "打印件预埋",
      qty: 16,
      color: "#b87333",
      dims: "M4 热熔",
      desc: "热风枪压入打印件",
      connects: ["F-07", "ST-bearing"],
      model: { type: "heatset", d: 0.004 },
    },
    {
      id: "F-09",
      cat: "fastener",
      name: "M3×8 内六角",
      spec: "圆柱头",
      qty: 24,
      color: "#c0c6cc",
      dims: "M3 × 8",
      desc: "电机座 / 打印件",
      connects: ["F-11", "ST-motor", "M-01"],
      model: { type: "screw", d: 0.003, len: 0.008, head: "socket" },
    },
    {
      id: "F-11",
      cat: "fastener",
      name: "M3 热熔螺母",
      spec: "打印件预埋",
      qty: 24,
      color: "#b87333",
      dims: "M3 热熔",
      desc: "打印件螺纹孔",
      connects: ["F-09"],
      model: { type: "heatset", d: 0.003 },
    },
    {
      id: "F-12",
      cat: "fastener",
      name: "M2×6 内六角",
      spec: "内六角/十字",
      qty: 16,
      color: "#c0c6cc",
      dims: "M2 × 6",
      desc: "ToF / 传感器",
      connects: ["ST-tof", "U-04"],
      model: { type: "screw", d: 0.002, len: 0.006, head: "socket" },
    },
    {
      id: "F-13",
      cat: "fastener",
      name: "M6×20 + 螺母",
      spec: "轴端",
      qty: 4,
      color: "#c0c6cc",
      dims: "M6 × 20",
      desc: "滚轮轴端固定",
      connects: ["SH-01", "ST-endcap"],
      model: { type: "screw", d: 0.006, len: 0.020, head: "hex" },
    },
    {
      id: "F-14",
      cat: "fastener",
      name: "轴用挡圈 Ø8",
      spec: "—",
      qty: 4,
      color: "#6a7078",
      dims: "Ø8 轴用",
      desc: "轴向定位",
      connects: ["SH-01", "BR-01"],
      model: { type: "circlip", d: 0.008 },
    },
    {
      id: "F-15",
      cat: "fastener",
      name: "顶丝 M4×4",
      spec: "无头",
      qty: 4,
      color: "#6a7078",
      dims: "M4 × 4",
      desc: "带轮 / 轮毂顶紧",
      connects: ["PU-01", "PU-02", "PU-03"],
      model: { type: "setscrew" },
    },
    {
      id: "F-16",
      cat: "fastener",
      name: "星形手拧螺母 M5",
      spec: "—",
      qty: 4,
      color: "#e85d04",
      dims: "M5 星形",
      desc: "滚轮滑轨锁紧，免工具",
      connects: ["E-07", "F-01"],
      model: { type: "starknob" },
    },
    {
      id: "F-17",
      cat: "fastener",
      name: "弹簧插销 Ø6",
      spec: "拉环式 · 行程8",
      qty: 2,
      color: "#c0c6cc",
      dims: "Ø6 · 行程 8",
      desc: "球筐快拆",
      connects: ["ST-corner", "E-08"],
      model: { type: "springpin" },
    },

    /* 电子 */
    {
      id: "U-01",
      cat: "elec",
      name: "香橙派 Zero 2W",
      spec: "1GB · Linux",
      qty: 1,
      color: "#22d866",
      dims: "SBC · USB×2",
      desc: "视觉/决策上位机",
      connects: ["U-03", "U-02", "U-06"],
      model: { type: "sbc" },
    },
    {
      id: "U-02",
      cat: "elec",
      name: "ESP32 DevKitC",
      spec: "WROOM · 双核 240MHz",
      qty: 1,
      color: "#22d866",
      dims: "DevKitC",
      desc: "运动/机构/安全下位机",
      connects: ["U-05", "U-06", "U-07"],
      model: { type: "esp32" },
    },
    {
      id: "U-03",
      cat: "elec",
      name: "UVC 摄像头",
      spec: "640×480 · ≥30FPS",
      qty: 1,
      color: "#0c2840",
      dims: "USB 免驱",
      desc: "球识别",
      connects: ["ST-cam", "U-01"],
      model: { type: "camera" },
    },
    {
      id: "U-04",
      cat: "elec",
      name: "VL53L1X ToF",
      spec: "0–4m · FOV 27°",
      qty: 3,
      color: "#22d866",
      dims: "I2C 模块",
      desc: "避障 + 硬急停",
      connects: ["ST-tof", "F-12", "U-02"],
      model: { type: "tof" },
    },
    {
      id: "U-05",
      cat: "elec",
      name: "TB6612FNG",
      spec: "双路 H 桥 · ≥3A/路",
      qty: 1,
      color: "#22d866",
      dims: "驱动模块",
      desc: "后驱 + 滚轮",
      connects: ["U-02", "M-01", "M-02"],
      model: { type: "driver" },
    },
    {
      id: "U-08",
      cat: "elec",
      name: "3S LiPo 5200",
      spec: "11.1V · ≥30C · XT60",
      qty: 1,
      color: "#3d5a80",
      dims: "3S 5200 mAh",
      desc: "主动力电池",
      connects: ["U-10", "U-11", "W-06"],
      model: { type: "lipo" },
    },

    /* 线材 */
    {
      id: "W-06",
      cat: "wire",
      name: "XT60 公+母",
      spec: "电池主回路",
      qty: 2,
      color: "#f0c040",
      dims: "XT60 对",
      desc: "动力插拔",
      connects: ["U-08", "U-13"],
      model: { type: "xt60" },
    },
    {
      id: "W-07",
      cat: "wire",
      name: "JST-SM 2P",
      spec: "电机接插件",
      qty: 4,
      color: "#e8e8e8",
      dims: "2P",
      desc: "电机可拔接插件",
      connects: ["M-01", "M-02", "U-05"],
      model: { type: "jst" },
    },
  ],

  /* ── 连接方式场景 ──
     parts: 参与件 id
     connectors: 可拖动的连接件（沿 axis 方向滑入）
     method: 文字说明
  */
  assemblies: [
    {
      id: "asm-corner",
      name: "型材 90° 角件连接",
      method: "T 螺母滑入 2020 槽 → 角件贴合 → M5×12 内六角锁紧",
      host: "E-01",
      guest: "E-02",
      connectors: [
        { id: "F-04", offset: [0, 0, 0], axis: "z", travel: 0.04, label: "T螺母 滑入槽" },
        { id: "ACC-CORNER", offset: [0.012, 0.012, 0], axis: "y", travel: 0.035, label: "角件 贴合" },
        { id: "F-03", offset: [0.022, 0.012, 0.028], axis: "z", travel: 0.04, label: "M5×12 旋紧" },
        { id: "F-01", offset: [0.022, 0.028, 0], axis: "y", travel: 0.035, label: "M5×10 锁槽" },
      ],
      steps: [
        "① T 螺母尖角朝内，从型材端滑入槽中对准孔位",
        "② 角件两翼贴合两根型材外侧",
        "③ M5×12 穿角件孔 → T 螺母，对角交替拧紧",
        "④ 长梁跨度大时加中间角件防扭",
      ],
    },
    {
      id: "asm-baseplate",
      name: "底板 ↔ 型材",
      method: "底板落在型材顶面/底面 → M5×8 穿板孔 → 法兰螺母背面锁紧",
      host: "PL-01",
      guest: "E-01",
      connectors: [
        { id: "F-02", offset: [0, 0.004, 0], axis: "y", travel: 0.03, label: "M5×8 穿板" },
        { id: "F-05", offset: [0, -0.008, 0], axis: "y", travel: 0.03, label: "法兰螺母" },
      ],
      steps: [
        "① 型材中心线投影到板上，孔距公差 ±0.2 mm",
        "② 底板铺上，M5×8 从板面穿入",
        "③ 背面法兰螺母锁紧，注意不压走线",
        "④ 四角优先锁，再锁中部，防板翘",
      ],
    },
    {
      id: "asm-roller",
      name: "滚轮轴系总成",
      method: "轴穿 TPU 套与端盖轴承 → 轴承落入座 → 轴端挡圈/M6 锁紧",
      host: "SH-01",
      guest: "ST-tpu",
      connectors: [
        { id: "ST-endcap", offset: [0, 0, 0.16], axis: "z", travel: 0.05, label: "端盖" },
        { id: "BR-01", offset: [0, 0, 0.19], axis: "z", travel: 0.04, label: "608 轴承" },
        { id: "ST-bearing", offset: [0, 0, 0.21], axis: "z", travel: 0.05, label: "轴承座" },
        { id: "F-14", offset: [0, 0, 0.24], axis: "z", travel: 0.03, label: "轴用挡圈" },
        { id: "F-13", offset: [0, 0, 0.26], axis: "z", travel: 0.03, label: "M6 轴端" },
      ],
      steps: [
        "① TPU 套水平慢速打印后压入铝管芯",
        "② 端盖热熔 M4 螺母，压入 608（铰孔 Ø22.0–22.1）",
        "③ 轴穿套与两端轴承，落入车架滑轨上的轴承座",
        "④ 轴端挡圈定位，M6 螺母防松；带轮顶丝锁轴",
        "⑤ 滑轨手拧星形螺母锁 X/Z 位置",
      ],
    },
    {
      id: "asm-motor",
      name: "电机座固定",
      method: "抱箍夹 JGB37 减速箱 → 法兰耳 M3×8 入热熔螺母",
      host: "ST-motor",
      guest: "M-01",
      connectors: [
        { id: "F-11", offset: [0, 0, 0.02], axis: "z", travel: 0.025, label: "M3 热熔螺母" },
        { id: "F-09", offset: [0, 0.03, 0], axis: "y", travel: 0.035, label: "M3×8 锁紧" },
        { id: "PU-01", offset: [0, 0, 0.08], axis: "z", travel: 0.04, label: "GT2 20T 带轮" },
        { id: "F-15", offset: [0.02, 0, 0.09], axis: "x", travel: 0.02, label: "顶丝 M4" },
      ],
      steps: [
        "① 打印座热风枪压入 M3 热熔螺母",
        "② 电机轴对准座孔，抱箍合上",
        "③ 法兰耳 4×M3×8 交叉拧紧",
        "④ 输出轴装 GT2 20T，顶丝对平面",
      ],
    },
    {
      id: "asm-steer",
      name: "前轮转向节",
      method: "主销穿转向节 → 球头拉杆连舵机臂 → 轮轴装 608",
      host: "ST-knuckle",
      guest: "SH-03",
      connectors: [
        { id: "BR-01", offset: [0.02, 0, 0], axis: "x", travel: 0.03, label: "轮轴 608" },
        { id: "S-01", offset: [-0.04, 0.02, 0], axis: "x", travel: 0.04, label: "舵机 + 臂" },
        { id: "ST-servo", offset: [-0.04, 0.0, 0], axis: "y", travel: 0.03, label: "舵机座" },
      ],
      steps: [
        "① 转向节主销孔铰至 Ø8，穿入 SH-03",
        "② 轮轴位压 608，装 Ø100 轮",
        "③ 中置 MG996R 装座，臂连横拉杆球头",
        "④ ±30° 行程试转，不刮底板/轮拱",
      ],
    },
    {
      id: "asm-basket",
      name: "球筐快拆",
      method: "角件装筐四角 → 沿定位轨滑入 → 弹簧插销锁定",
      host: "ST-corner",
      guest: "E-08",
      connectors: [
        { id: "F-17", offset: [0, 0, 0.04], axis: "z", travel: 0.05, label: "弹簧插销" },
      ],
      steps: [
        "① 8 个 PETG 角件固定筐四角（上下各一）",
        "② 筐沿 E-08 定位轨推入平台顶",
        "③ 两侧弹簧插销拉环插入锁孔",
        "④ 取筐时拉环拔出，双手握提手提起",
      ],
    },
    {
      id: "asm-bearing",
      name: "轴承座安装",
      method: "608 压入打印座 → M4×12 穿座耳入热熔螺母固定到滑轨",
      host: "ST-bearing",
      guest: "BR-01",
      connectors: [
        { id: "BR-01", offset: [0, 0, 0], axis: "y", travel: 0.03, label: "608 压入" },
        { id: "F-08", offset: [0.02, 0, 0], axis: "x", travel: 0.025, label: "M4 热熔" },
        { id: "F-07", offset: [0.02, 0.02, 0], axis: "y", travel: 0.03, label: "M4×12" },
      ],
      steps: [
        "① 孔打印补偿 +0.2，铰到 Ø22.0–22.1",
        "② 608 双面密封朝外，轻打或压入",
        "③ 座耳热熔 M4 螺母",
        "④ M4×12 固定到 E-07 滑轨槽内 T 母",
      ],
    },
    {
      id: "asm-servo",
      name: "舵机座装配",
      method: "MG996R 放入座槽 → 侧面 M3 锁紧 → 臂盘 + 球头扣",
      host: "ST-servo",
      guest: "S-01",
      connectors: [
        { id: "F-11", offset: [0, 0, 0.015], axis: "z", travel: 0.02, label: "热熔螺母" },
        { id: "F-09", offset: [0, 0.025, 0], axis: "y", travel: 0.03, label: "M3×8" },
      ],
      steps: [
        "① 座槽按 40×20 舵机体校核间隙",
        "② 舵机中位 1500μs 后装臂",
        "③ 侧面 4×M3 锁紧，线缆从座后出",
        "④ 供电用独立 5V≥3A，勿与逻辑共小 BEC",
      ],
    },
    {
      id: "asm-ecu",
      name: "电控密封舱",
      method: "模块装入盒底 → 盖唇边对齐 → 4×M3 锁盖",
      host: "ST-ecu",
      guest: "ST-lid",
      connectors: [
        { id: "U-02", offset: [0, 0.02, 0], axis: "y", travel: 0.035, label: "ESP32" },
        { id: "U-01", offset: [0, 0.035, 0], axis: "y", travel: 0.04, label: "香橙派" },
        { id: "ST-lid", offset: [0, 0.06, 0], axis: "y", travel: 0.04, label: "盖" },
        { id: "F-09", offset: [0.04, 0.055, 0], axis: "y", travel: 0.03, label: "M3×8 锁盖" },
      ],
      steps: [
        "① 盒开口朝上打印，壁 3 周长",
        "② 底部先装电源分配与 BEC",
        "③ 上层 ESP32 + 香橙派，走线孔护线圈",
        "④ 盖唇边对准，4×M3 均匀锁紧",
        "⑤ 共地星形：结构铝与电池负单点",
      ],
    },
    {
      id: "asm-gt2",
      name: "GT2 同步带传动",
      method: "20T 上电机轴 / 40T 上滚轮轴 → 闭环带套上 → 惰轮张紧",
      host: "PU-01",
      guest: "PU-02",
      connectors: [
        { id: "BL-01", offset: [0, 0, 0.01], axis: "z", travel: 0.03, label: "闭环带" },
        { id: "F-15", offset: [0.02, 0, 0], axis: "x", travel: 0.02, label: "顶丝" },
      ],
      steps: [
        "① 下单前按 L≈2C+π(D1+D2)/2 算周长",
        "② 小轮 20T 装电机 D 轴，顶丝对平面",
        "③ 大轮 40T 装滚轮轴/通轴",
        "④ 闭环带先套大轮再扳上小轮",
        "⑤ 光面惰轮压紧背面，挠度约 5mm",
      ],
    },
  ],
};
